In [2]:
!pip install joblib

  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)


In [8]:
import os
import matplotlib.pyplot as plt
import numpy as np
import joblib # to save model
plt.style.use("fivethirtyeight")


In [17]:
class Perceptron:
    def __init__(self,eta:float=None,epochs:int=None):
        self.weights=np.random.randn(3)*1e-4
        self.eta = eta # learning rate
        self.epochs=epochs # iterations
        
    def fit(self,x,y):
        self.x=x
        self.y=y
        
        x_with_bias = np.c_[self.x, -np.ones((len(self.x),1))]
        print(f"x with bias \n{x_with_bias}")
        

In [22]:
obj=Perceptron(eta=0.01,epochs=10)

In [23]:
obj.eta

0.01

In [24]:
obj.epochs

10

In [25]:
obj.weights

array([-1.06060989e-05,  2.34175191e-04, -1.29830635e-04])

In [29]:
x=np.ones((4,2))

In [30]:
x

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
y=-np.ones((4,2))

In [32]:
y

array([[-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.]])

In [33]:
obj.fit(x,y)

x with bias 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
