In [135]:
!pip install joblib

In [136]:
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import joblib # to save model
plt.style.use("fivethirtyeight")


In [137]:
class Perceptron:
    def __init__(self,eta:float=None,epochs:int=None):
        self.weights=np.random.randn(3)*1e-4
        self.eta = eta # learning rate
        self.epochs=epochs # iterations
        
    def _z_outcome(self,inputs,weights):
        return np.dot(inputs,weights)
    
    def activation_function(self,z):
        return np.where(z > 0, 1, 0)
        
    def fit(self,x,y):
        self.x=x
        self.y=y
        
        x_with_bias = np.c_[self.x, -np.ones((len(self.x),1))]
        print(f"x with bias: \n{x_with_bias}")
        
    # now starts training
    # step1:- go for a forward pass i.e, calculating z value by multiply input with weights.
        for epochs in range(self.epochs):
            print("--"*10)
            print(f"for each >> {epochs + 1}")
            print("--"*10)
            z=self._z_outcome(x_with_bias,self.weights)
            y_hat = self.activation_function(z)
            print(f"predicted value after forward pass: \n{y_hat}")
            self.error=self.y - y_hat
            print(f"error:\n{self.error}")      
            self.weights=self.weights+self.eta*np.dot(x_with_bias.T,self.error)
            print(f"updated weights after epoch:{epochs+1}/{self.epochs}: \n{self.weights}")
            print(f"##"*10)
    def Predict(self,x):
        x_with_bias=np.c_[x, -np.ones((len(x),1))]
        z=self._z_outcome(x_with_bias,self.weights)
        return self.activation_function(z)
            

In [138]:
OR= {
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y":[0,1,1,1]
}
df_OR=pd.DataFrame(OR)
df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [139]:
def Prepare_data(df,target_col="y"):
    x=df.drop(target_col,axis=1)
    y=df[target_col]
    return x,y

In [140]:
x,y=Prepare_data(df_OR)
ETA=0.1
EPOCHS=10
model_or=Perceptron(eta=ETA,epochs=EPOCHS)

In [141]:
x,y=Prepare_data(df_OR)
x

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [142]:
y

0    0
1    1
2    1
3    1
Name: y, dtype: int64

In [143]:
model_or.fit(x,y)

x with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for each >> 1
--------------------
predicted value after forward pass: 
[0 1 0 1]
error:
0    0
1    0
2    1
3    0
Name: y, dtype: int64
updated weights after epoch:1/10: 
[ 1.00034885e-01  7.49567536e-05 -9.99327363e-02]
####################
--------------------
for each >> 2
--------------------
predicted value after forward pass: 
[1 1 1 1]
error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch:2/10: 
[1.00034885e-01 7.49567536e-05 6.72636584e-05]
####################
--------------------
for each >> 3
--------------------
predicted value after forward pass: 
[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch:3/10: 
[1.00034885e-01 7.49567536e-05 6.72636584e-05]
####################
--------------------
for each >> 4
--------------------
predicted value after forward pass: 
[0 1 1 1]
error:
0    0
1    0
2    0
3 

In [144]:
model_or.Predict(x)

array([0, 1, 1, 1])

In [145]:
model_or.Predict(x=[[0,0]])

array([0])

AND gate Implementation.

In [146]:
AND= {
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y":[0,0,0,1]
}
df_AND=pd.DataFrame(AND)
df_AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [147]:
x,y=Prepare_data(df_AND)
ETA=0.1
EPOCHS=10
model_AND=Perceptron(eta=ETA,epochs=EPOCHS)

In [148]:
x

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [149]:
y

0    0
1    0
2    0
3    1
Name: y, dtype: int64

In [150]:
model_AND.fit(x,y)

x with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for each >> 1
--------------------
predicted value after forward pass: 
[1 1 1 1]
error:
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch:1/10: 
[-0.09994067 -0.10002572  0.29997247]
####################
--------------------
for each >> 2
--------------------
predicted value after forward pass: 
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch:2/10: 
[ 5.93327614e-05 -2.57215138e-05  1.99972466e-01]
####################
--------------------
for each >> 3
--------------------
predicted value after forward pass: 
[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch:3/10: 
[0.10005933 0.09997428 0.09997247]
####################
--------------------
for each >> 4
--------------------
predicted value after forward pass: 
[0 1 1 1]
error:
0    0
1   -1
2   -1
3    0
Name: y, dtype: 

In [151]:
model_AND.Predict(x=[[1,1]])

array([1])

In [152]:
model_AND.Predict(x=[[0,1]])

array([0])

In [153]:
model_AND.Predict(x)

array([0, 0, 0, 1])

XOR Implementation

In [154]:
XOR= {
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y":[0,1,1,0]
}
df_XOR=pd.DataFrame(XOR)
df_XOR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [160]:
x

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [161]:
y

0    0
1    1
2    1
3    0
Name: y, dtype: int64

In [165]:
x,y=Prepare_data(df_XOR)
ETA=0.1
EPOCHS=10
model_XOR=Perceptron(eta=ETA,epochs=EPOCHS)

In [166]:
model_XOR.fit(x,y)

x with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for each >> 1
--------------------
predicted value after forward pass: 
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights after epoch:1/10: 
[-0.10000665 -0.09999138  0.19993707]
####################
--------------------
for each >> 2
--------------------
predicted value after forward pass: 
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epoch:2/10: 
[-6.64917131e-06  8.62224566e-06 -6.29272542e-05]
####################
--------------------
for each >> 3
--------------------
predicted value after forward pass: 
[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights after epoch:3/10: 
[-0.10000665 -0.09999138  0.19993707]
####################
--------------------
for each >> 4
--------------------
predicted value after forward pass: 
[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtyp

In [172]:
model_XOR.Predict(x=[[0,0]])#output will not come here, output is wrong becoz OR and AND gates are linear where as XOR gate is non-linear.

array([1])